### ISSUE TITLE
Release SIA Review and approval tracking

### ISSUE THREAD

**Issue by JonathanLerner54** [USDAForestService/fs-open-forest-platform#829]
## Need to track the SIA document review  and approval for each release
Currently this is being conducted via emails which is not optimal from a management visibility perspective.

## Current Process
1. Operations Team is sent a request to move release to Production.  Prior to implementing the release, 
2. An Email is sent from Operations Team to ISSO to inform them that a release was pending and a request for security review and approval to proceed with publishing the release to production.
      - Attached to that email is the SIA that highlighted the changes and the Risk associated with them
Items within the SIA will be checked if they affect the security or not.
3. Review the SIA document which includes reference related release issue numbers to insure all security issues were addressed.
4. ISSO reviews and returns for corrections (if needed) and once concerns are addressed approves the release action.

## Options are:
1.  Open a separate issue to track the Security and Operations with reference back to the Production release issue with SIA document attached
      -  Issue is that SIA document could contain possible vulnerability or other risk identifier
2.   Open a separate issue to track the Security and Operations with reference back to the Production release issue with SIA document stored on Pinyon and reference the document in the issue description.  
      -  This would address issue identified in item 1
3.  Update original issue with SIA approval status and release completion information, then close issue and either attach SIA document or a reference link to Pinyon based on decision of 1&2.

**Comment by ASprinkle** [comment]
@JonathanLerner54 @aaronburk is this story suited better for the Program Board?

**Comment by ASprinkle** [comment]
@carlsonem is this a story for the Program board? or here?

**Comment by ASprinkle** [comment]
Update from stand up: Here is good - checks prior to production. pick regular times for release and know who's involved in the process so that we can plan.

**Comment by mwreiss** [comment]
@JonathanLerner54  @smahmudFS This issue could be closed now.  We are well organized in the prod SIA release process, if you agree?

**Comment by JonathanLerner54** [comment]
Yes I recommend closure of this item as well.
